// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: System.Reflection.AssemblyCompanyAttribute("DSPLCServer.FS")>]
[<assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")>]
[<assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")>]
[<assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+752aa76facfec03a7b74043b117986f8ddb921b1")>]
[<assembly: System.Reflection.AssemblyProductAttribute("DSPLCServer.FS")>]
[<assembly: System.Reflection.AssemblyTitleAttribute("DSPLCServer.FS")>]
[<assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")>]
do()
